local:
  build: .
  ports:
    - 8080
  volumes:
    - ./data:/var/jenkins_home
    - /var/run/docker.sock:/tmp/docker.sock
  environment:
    VIRTUAL_PORT: 8080
    VIRTUAL_HOST: builder.local.dockito.org
